name: ADDGCN_Baseline
seed: 1

data:
  root: /kaggle/input/datasets/ashery/chexpert
  train_csv: /kaggle/working/TULIP-MedML/data/train_small_v2.csv
  val_csv: /kaggle/working/TULIP-MedML/data/valid.csv
  val_uncertain_csv: /kaggle/working/TULIP-MedML/data/val_uncertain.csv
  word_vec: /kaggle/working/TULIP-MedML/data/chexpert_glove_word2vec.npy
  uncertain: keep
  img_size: 448

model:
  pretrained: true

train:
  epochs: 20
  batch_size: 16
  workers: 4
  gpu_ids: [0, 1]
  lr: 0.05
  lrp: 0.1
  momentum: 0.9
  weight_decay: 0.0001
  epoch_step: []
  max_clip_grad_norm: 10.0

output:
  save_dir: /kaggle/working/checkpoints/addgcn_baseline
