# C2: Swin-Base + GloVe + BCE  <- thay backbone
name: C2_swin
seed: 42

data:
  root:      /kaggle/input/datasets/ashery/chexpert
  train_csv: /kaggle/working/TULIP-MedML/data/train_small_v2.csv
  val_csv:   /kaggle/working/TULIP-MedML/data/valid.csv
  val_uncertain_csv: /kaggle/working/TULIP-MedML/data/val_uncertain.csv
  word_vec:  /kaggle/working/TULIP-MedML/data/chexpert_glove_word2vec.npy
  adj:       /kaggle/working/TULIP-MedML/data/chexpert_adj.pkl
  uncertain: keep
  img_size:  224   # Swin pretrained trên 224

model:
  backbone:   swin_b   #  thay đổi duy nhất so với C1 (Swin-Base)
  pretrained: true
  gcn_in:     300
  t:          0.4

loss:
  type: bce

train:
  epochs:      20
  batch_size:  16
  lr:          0.01
  lrp:         0.1
  momentum:    0.9
  weight_decay: 0.0001
  epoch_step:  []
  workers:     4

output:
  save_dir: /kaggle/working/checkpoints/c2
  log_dir:  /kaggle/working/logs/c2