# C3: ResNet-101 + BiomedCLIP init + BCE  <- thay node init
name: C3_biomedclip
seed: 42

data:
  root:      /kaggle/input/datasets/ashery/chexpert
  train_csv: /kaggle/working/TULIP-MedML/data/train_small_v2.csv
  val_csv:   /kaggle/working/TULIP-MedML/data/valid.csv
  val_uncertain_csv: /kaggle/working/TULIP-MedML/data/val_uncertain.csv
  word_vec:  /kaggle/working/TULIP-MedML/data/chexpert_biomedclip_vec.npy  # file khác
  adj:       /kaggle/working/TULIP-MedML/data/chexpert_adj.pkl
  uncertain: keep
  img_size:  448

model:
  backbone:   resnet101
  pretrained: true
  gcn_in:     512   # BiomedCLIP output 512 chiều
  t:          0.4

loss:
  type: bce

train:
  epochs:      20
  batch_size:  16
  lr:          0.01
  lrp:         0.1
  momentum:    0.9
  weight_decay: 0.0001
  epoch_step:  [12 , 17]
  workers:     4

output:
  save_dir: /kaggle/working/checkpoints/c3
  log_dir:  /kaggle/working/logs/c3