# C4: ResNet-101 + GloVe + UA-ASL  <- thay loss
name: C4_uaasl
seed: 42

data:
  root:      /kaggle/input/datasets/ashery/chexpert
  train_csv: /kaggle/working/TULIP-MedML/data/train_small.csv
  val_csv:   /kaggle/working/TULIP-MedML/data/valid.csv
  word_vec:  /kaggle/working/TULIP-MedML/data/chexpert_glove_word2vec.npy
  adj:       /kaggle/working/TULIP-MedML/data/chexpert_adj.pkl
  uncertain: keep   # UA-ASL nhận -1 trực tiếp, KHÔNG remap
  img_size:  448

model:
  backbone:   resnet101
  pretrained: true
  gcn_in:     300
  t:          0.4

loss:
  type:       ua_asl   #  thay đổi duy nhất so với C1
  gamma_pos:  0
  gamma_neg:  4
  lambda_unc: 0.5

train:
  epochs:      20
  batch_size:  16
  lr:          0.01
  lrp:         0.1
  momentum:    0.9
  weight_decay: 0.0001
  epoch_step:  [30]
  workers:     4

output:
  save_dir: /kaggle/working/checkpoints/c4
  log_dir:  /kaggle/working/logs/c4