# C5: Swin-T + BiomedCLIP + UA-ASL  <- TULIP-MedML đầy đủ
name: C5_tulip_medml
seed: 42

data:
  root:      /kaggle/input/datasets/ashery/chexpert
  train_csv: /kaggle/working/TULIP-MedML/data/train_small_v2.csv
  val_csv:   /kaggle/working/TULIP-MedML/data/valid.csv
  val_uncertain_csv: /kaggle/working/TULIP-MedML/data/val_uncertain.csv
  word_vec:  /kaggle/working/TULIP-MedML/data/chexpert_biomedclip_vec.npy
  adj:       /kaggle/working/TULIP-MedML/data/chexpert_adj.pkl
  uncertain: keep
  img_size:  224

model:
  backbone:   swin_t
  pretrained: true
  gcn_in:     512
  t:          0.4

loss:
  type:       ua_asl
  gamma_pos:  0.0
  gamma_neg:  4.0
  margin:     0.05
  lambda_unc: 0.5
  alpha:      0.5
  reduction:  'mean'
  disable_torch_grad_focal_loss: True

train:
  epochs:      20
  batch_size:  16
  lr:          0.01   
  lrp:         0.1
  momentum:    0.9
  weight_decay: 0.0001
  # epoch_step:  [12 , 17]
  workers:     4

output:
  save_dir: /kaggle/working/checkpoints/c5
  log_dir:  /kaggle/working/logs/c5